server:
  session:
    timeout: 800000
    cookie:
      name: JSESSIONID
shiny:
  proxy:
    title: Open Analytics Shiny Proxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 6000000
    container-wait-time: 120000
    container-wait-timeout: 5000
    port: 8080
    authentication: simple
    admin-groups: scientists
    hazelcast:
      server: 192.168.0.210:5701
    # Example: 'simple' authentication configuration
    users:
    - name: j
      password: p
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    # Example: 'ldap' authentication configuration
    ldap:
      url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      user-dn-pattern: uid={0}
      group-search-base:
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=read-only-admin,dc=example,dc=com
      manager-password: password
    # Docker configuration
    docker:
      url: http://localhost:2375
      kubernetes: false
      kubernetes-image-pull-policy: Always
      kubernetes-image-pull-secrets: imgpullsecret
      internal-networking: false
      port-range-start: 3838
      port-range-max: 4000
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists, mathematicians
    kubernetes-namespace: shiny
    kubernetes-memory-request: 600Mb
    kubernetes-memory-limit: 1Gi
    kubernetes-cpu-request: 500m
    kubernetes-cpu-limit: 1
  - name: 06_tabsets
    docker-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists

logging:
  level:
    debug
  file:
    shinyproxy1.log